more mysql2, salor-virtual can install gems

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -64,10 +64,12 @@ case "$1" in
       echo "pcspkr" >> /etc/modules;
     fi
     
-    if [ ! -e /usr/lib/ruby/vendor_ruby/mysql2.rb ]; then
-      echo "  postinst: This is an older Debian version than Jessie. We have to run bundle install to get gems from rubygems.org."
-      cd /usr/share/salor-hospitality/source
-      bundle install
+    dpkg-query -Wf'${db:Status-abbrev}' salor-virtual 2>/dev/null | grep -q '^i'
+    if [ "$?" = "1" ]; then
+      echo "  postinst: Some of the required gems are not available as Debian packages. We have to run bundle install to download gems from rubygems.org."
+      salor-installgems h
+    else
+      echo "  postinst: All required gems are available as Debian packages. Nothing to be done."
     fi
   ;;
 
