more mysql replication work

diff --git a/debian/bin/salor-hospitality_setup-db-replication b/debian/bin/salor-hospitality_setup-db-replication
--- a/debian/bin/salor-hospitality_setup-db-replication
+++ b/debian/bin/salor-hospitality_setup-db-replication
@@ -1,10 +1,9 @@
 #!/bin/bash
-
-mycnf=/etc/mysql/my.cnf
-servertype=$1
-
-
 cd /etc/mysql
+mycnf=/etc/mysql/my.cnf
+
+echo -ne "Please specify the server type {master|slave}: "
+read servertype
 
 if [ "$servertype" = "master" ]; then
   if [ ! -e ca-key.pem ]; then
@@ -23,18 +22,19 @@ if [ "$servertype" = "master" ]; then
     echo "sign SLAVE certificate sign request (outputs signed certificate)"
     openssl x509 -req -in slave-req.pem -CA ca-crt.pem -CAkey ca-key.pem -set_serial 01 -out slave-crt.pem
     
-    echo "Now copy ca-crt.pem slave-key.pem slave-crt.pem to /etc/mysql of SLAVE"
+    echo "Certificate generation done. Now copy /etc/mysql/{ca-crt, slave-key, slave-crt}.pem to /etc/mysql of SLAVE."
   else
     echo "Master keys already exist. Nothing to be done."
   fi
 elif [ "$servertype" = "slave" ]; then
   if [ ! -e slave-key.pem ]; then
-    echo "download and copy ca-crt.pem slave-key.pem slave-crt.pem to /etc/mysql"
+    echo "Copy /etc/mysql/{ca-crt, slave-key, slave-crt}.pem from MASTER to /etc/mysql of this server and run this script again."
+    exit 1
   else
-    echo "Slave keys already exist. Nothing to be done."
+    echo "SLAVE keys already exist. Nothing to be done."
   fi
 else
-  echo "You have to specify 'master' or 'slave' as first command line parameter."
+  echo "Invalid input."
   exit 1
 fi
 
@@ -43,52 +43,74 @@ if [ "$2" != "" ]; then
   siteid=$2
 fi
 
+echo -ne "Please specify the MASTER IP: "
+read ip_master
 
-database_config_file=/etc/salor-hospitality/$siteid/database.yml
-
-usernameline=`grep 'username:' $database_config_file | head -1`
-username=`echo $usernameline | sed -e 's/username: //'`
-databaseline=`grep 'database:' $database_config_file | head -1`
-database=`echo $databaseline | sed -e 's/database: //'`
-passwordline=`grep 'password:' $database_config_file | head -1`
-password=`echo $passwordline | sed -e 's/password: //'`
-
-echo "username is $username"
-echo "password is $password"
-echo "database is $database"
 
 if [ ! -e $mycnf.orig ]; then
   echo "Backing up my.cnf before modification."
   cp $mycnf $mycnf.orig
+  
+  echo -ne "Please specify the replication username (default is salorreplicator): "
+  read replication_username
+  if [ "$replication_username" == "" ]; then replication_username="salorreplicator"; fi
+  
+  echo -ne "Please specify the replication password (default is xxx): "
+  read replication_password
+  if [ "$replication_password" == "" ]; then replication_password="xxx"; fi
 
   if [ "$servertype" = 'master' ]; then
+  
+    echo -ne "Please specify the SLAVE IP or FQDM (default is %): "
+    read slave_host
+    if [ "$slave_host" == "" ]; then slave_host="%"; fi
+
     sed -i 's/^bind-address/#bind-address/' $mycnf
     sed -i 's/#server-id.*$/server-id = 1/' $mycnf
     sed -i 's/#log_bin/log_bin/' $mycnf
-    sed -i "s/#binlog_do_db.*$/binlog_do_db=${database}\\`echo -e '\n\r'`#binlog_do_db = include_database_name/" $mycnf
+    sed -i "s/#binlog_do_db.*$/binlog_do_db=${database}\\`echo -e '\n'`#binlog_do_db = include_database_name/" $mycnf
     
-    sed -i "s/^#binlog_ignore_db.*$/relay-log = \/var\/lib\/mysql\/mysql-relay-bin\\`echo -e '\n\r'`relay-log-index = \/var\/lib\/mysql\/mysql-relay-bin.index/" $mycnf
+    sed -i "s/^#binlog_ignore_db.*$/relay-log = \/var\/lib\/mysql\/mysql-relay-bin\\`echo -e '\n'`relay-log-index = \/var\/lib\/mysql\/mysql-relay-bin.index/" $mycnf
     
-    sed -i "s/# ssl-ca.*/ssl\\`echo -e '\n\r'`ssl-ca=\/etc\/mysql\/ca-crt.pem/" $mycnf
+    sed -i "s/# ssl-ca.*/ssl\\`echo -e '\n'`ssl-ca=\/etc\/mysql\/ca-crt.pem/" $mycnf
     sed -i "s/# ssl-cert.*$/ssl-cert=\/etc\/mysql\/master-crt.pem/" $mycnf
     sed -i "s/# ssl-key.*$/ssl-key=\/etc\/mysql\/master-key.pem/" $mycnf
     
-    echo "CREATE USER 'salorreplicator6'@'%' IDENTIFIED BY 'salorreplicator6'; GRANT REPLICATION SLAVE ON *.* TO 'salorreplicator6'@'%' REQUIRE SSL; FLUSH PRIVILEGES;" | mysql -u root -proot
+    echo "CREATE USER '$replication_username'@'$slave_host' IDENTIFIED BY '$replication_password'; GRANT REPLICATION SLAVE ON *.* TO '$replication_username'@'$slave_host' REQUIRE SSL; FLUSH PRIVILEGES;" | mysql -u root -proot
 
   elif [ $servertype = 'slave' ]; then
+  
+    echo -ne "Please specify the MASTER IP or FQDM: "
+    read master_host
+    if [ "$master_host" == "" ]; then
+      echo "Need master IP or FQDM. Exiting..."
+      exit 1
+    fi
+    
     sed -i 's/#server-id.*$/server-id = 2/' $mycnf
     sed -i 's/#log_bin/log_bin/' $mycnf
-    sed -i "s/#binlog_do_db.*$/binlog_do_db=${database}\\`echo -e '\n\r'`#binlog_do_db = include_database_name/" $mycnf
+    sed -i "s/#binlog_do_db.*$/binlog_do_db=${database}\\`echo -e '\n'`#binlog_do_db = include_database_name/" $mycnf
     
-    sed -i "s/^#binlog_ignore_db.*$/relay-log = \/var\/lib\/mysql\/mysql-relay-bin\\`echo -e '\n\r'`relay-log-index = \/var\/lib\/mysql\/mysql-relay-bin.index\\`echo -e '\n\r'`master-host = MASTER_IP\\`echo -e '\n\r'`master-user = salorreplicator6\\`echo -e '\n\r'`master-password = salorreplicator6\\`echo -e '\n\r'`report-host = 127.0.0.1/" $mycnf
+    sed -i "s/^#binlog_ignore_db.*$/relay-log = \/var\/lib\/mysql\/mysql-relay-bin\\`echo -e '\n'`relay-log-index = \/var\/lib\/mysql\/mysql-relay-bin.index\\`echo -e '\n'`master-host = ${master_host}\\`echo -e '\n'`master-user = ${replication_username}\\`echo -e '\n'`master-password = ${replication_password}\\`echo -e '\n'`report-host = 127.0.0.1/" $mycnf
     
-    sed -i "s/# ssl-ca.*/ssl\\`echo -e '\n\r'`ssl-ca=\/etc\/mysql\/ca-crt.pem/" $mycnf
+    sed -i "s/# ssl-ca.*/ssl\\`echo -e '\n'`ssl-ca=\/etc\/mysql\/ca-crt.pem/" $mycnf
     sed -i "s/# ssl-cert.*$/ssl-cert=\/etc\/mysql\/slave-crt.pem/" $mycnf
     sed -i "s/# ssl-key.*$/ssl-key=\/etc\/mysql\/slave-key.pem/" $mycnf
   fi
   
   service mysql restart
-  echo "show variables like '%ssl%';" | mysql -u root -proot
+  
+  echo -ne "Please specify the administraive username of mysql (default is root): "
+  read mysql_admin_username
+  if [ "$mysql_admin_username" == "" ]; then mysql_admin_username"root"; fi
+  echo -ne "Please specify the administraive password of mysql (default is root): "
+  read mysql_admin_password
+  if [ "$mysql_admin_password" == "" ]; then mysql_admin_password="root"; fi
+  
+  echo ""
+  echo "Check if mysql is now SSL enabled:"
+  echo ""
+  echo "show variables like '%ssl%';" | mysql -u ${mysql_admin_username} -p${mysql_admin_password}
 else
   echo "This script already has modified /etc/mysl/my.cnf. Not running twice. You have to manually inspect the changes."
 fi
